[package]
name = "mlkem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-order = { version = "0.3.0", default-features = false}
hex = { version = "0.4.3", default-features = false}
hex-literal = { version = "0.4.1", default-features = false}
rand = { version = "0.8.5", default-features = false, features = ["alloc"] }
rand_chacha = {version = "0.3.1", default-features = false}
sha3 = {version = "0.10.8", default-features = false}

[profile.test]
opt-level = 3