[package]
name = "mlkem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-order = "0.3.0"
hex = "0.4.3"
hex-literal = "0.4.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
sha3 = "0.10.8"
