[package]
name = "mlkem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-bigint = { git = "https://github.com/RustCrypto/crypto-bigint.git", tag = "v0.6.0-pre.12" }
rand = "0.8.5"